#server:
#  port: 8081
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/skillsell?serverTimezone=UTC
#    username: root
#    password: 123456
#  redis:
#    host: localhost
#    port: 6379
#  cloud:
#    nacos:
#      discovery:
#        service: gateway-service
#      server-addr: localhost:8848
#    sentinel:
#      transport:
#        dashboard: localhost:8080
