server:
  port: 13000
spring:
  cloud:
    nacos:
      discovery:
        service: skillsell-service
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  datasource:
    url: jdbc:mysql://localhost:3306/skillsell?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/user/current/get
      id: skillsell-service