management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
  # 设置链路模式
      filter:
        enabled: false
  application:
      name: centinel-server
server:
  port: 9000