server:
  port: 11000
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        service: stock-service
        group: SEATA_GROUP
  datasource:
    url: jdbc:mysql://localhost:3306/stockdb?serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: stock-server   #此处需要新增 不然seata会报错
seata:
  enabled: true
  # 和注册到nacos的 配置 后缀相同
  tx-service-group: order-service
  config:
    type: nacos
    nacos:
      namespace: public
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: public
      userName: "nacos"
      password: "nacos"